# fly.toml app configuration file generated for fast-api-image-classification on 2024-01-28T14:07:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-api-image-classification'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
