def get_languages_options():
    """
        Return a list of languages available 
    """
    return [
        {
            'label': f"{label} - {language.upper()}",
            'value': language
        } 
        for label, language in zip (['Dansk', 'Deutsch', 'English', 'Français'], ['da','de','en','fr']) 
        ]

def get_translate():
    """
        Return a dict of sentence to be translated into differents languages
    """
    return {
    'en': {
        'choose_country': 'Choose a country',
        'search_product': 'Search a product',
        'picture_search_beta': "Picture search (in beta) 📷",
        'advanced_search': 'Advanced search 🔍',
        'browsing_history': 'Browsing history',
        'displaying_5_products': 'Displaying 5 products',
        'displaying_10_products': 'Displaying 10 products',
        'displaying_15_products': 'Displaying 15 products',
        'displaying_20_products': 'Displaying 20 products',
        'advanced_search_label': 'ADVANCED SEARCH',
        'choose_pnns_group_1': 'Choose a PNNS group 1 (optional)',
        'choose_pnns_group_2': 'Choose a PNNS group 2 (optional)',
        'search_product_optional': 'Search a product (e.g. \'milk\') (optional)',
        'choose_nutritious_plan': 'Choose a nutritious plan (optional)',
        'energy_kcal_100g': 'Energy kcal/100g',
        'energy-kcal_100g': 'Energy kcal/100g',
        'energy_100g': 'Energy kcal/100g',
        'fat_g_100g': 'Fat g/100g',
        'fat_100g': 'Fat g/100g',
        'saturated_fat_g_100g': 'Saturated_fat g/100g',
        'saturated-fat_100g': 'Saturated_fat g/100g',
        'carbohydrates_g_100g': 'Carbohydrates g/100g',
        'carbohydrates_100g': 'Carbohydrates g/100g',
        'fiber_g_100g': 'Fiber g/100g',
        'fiber_100g': 'Fiber g/100g',
        'proteins_g_100g': 'Proteins g/100g',
        'proteins_100g': 'Proteins g/100g',
        'salt_g_100g': 'Salt g/100g',
        'salt_100g': 'Salt g/100g',
        'macronutrients_g_100g': 'Macronutrients g/100g',
        'macronutrients_100g': 'Macronutrients g/100g',
        'search': 'Search',
        'no_image_available': 'No image available',
        'choose_nutrients': 'Choose nutrients',
        'upload_image': 'Upload image [max 15MB] (.JPEG, .PNG, .JPG)',
        'search_pnns_groups_1': 'Search pnns_groups_1',
        'search_pnns_groups_2': 'Search pnns_groups_2',
        'clear_image': 'Clear image',
        'best_recommended_products': 'BEST RECOMMENDED PRODUCTS BY CATEGORY',
        'product_not_found': 'Product not found, search for another one',
        'product_not_available': 'The product is not available',
        'product_name': 'Product name',
        'product_code': 'Product code',
        'products': 'products',
        'Composite foods': 'Composite foods',
        'Fruits and vegetables': 'Fruits and vegetables',
        'Cereals and potatoes': 'Cereals and potatoes',
        'Fat and sauces': 'Fat and sauces',
        'Salty snacks': 'Salty snacks',
        'Beverages': 'Beverages',
        'Sugary snacks': 'Sugary snacks',
        'Fish Meat Eggs': 'Fish Meat Eggs',
        'Milk and dairy products': 'Milk and dairy products',
        'referenced_products': 'Referenced products',
        "United States": 'United States', 
        "France": 'France', 
        "Germany": 'Germany', 
        "United Kingdom": 'United kingdom',
        'Pizza pies and quiches': 'Pizza pies and quiches',
        'Fruits': 'Fruits',
        'Bread': 'Bread',
        'Dressings and sauces': 'Dressings and sauces',
        'Salty and fatty products': 'Salty and fatty products',
        'Sweetened beverages': 'Sweetened beverages',
        'Sweets': 'Sweets',
        'Biscuits and cakes': 'Biscuits and cakes',
        'Pastries': 'Pastries',
        'Fish and seafood': 'Fish and seafood',
        'One-dish meals': 'One-dish meals',
        'Appetizers': 'Appetizers',
        'Cheese': 'Cheese',
        'Fats': 'Fats',
        'Processed meat': 'Processed meat',
        'Sandwiches': 'Sandwiches',
        'Vegetables': 'Vegetables',
        'Breakfast cereals': 'Breakfast cereals',
        'Chocolate products': 'Chocolate products',
        'Unsweetened beverages': 'Unsweetened beverages',
        'Dried fruits': 'Dried fruits',
        'Meat': 'Meat',
        'Cereals': 'Cereals',
        'Eggs': 'Eggs',
        'Plant-based milk substitutes': 'Plant-based milk substitutes',
        'Legumes': 'Legumes',
        'Teas and herbal teas and coffees': 'Teas and herbal teas and coffees',
        'Dairy desserts': 'Dairy desserts',
        'Nuts': 'Nuts',
        'Fruit juices': 'Fruit juices',
        'Milk and yogurt': 'Milk and yogurt',
        'Artificially sweetened beverages': 'Artificially sweetened beverages',
        'Potatoes': 'Potatoes',
        'Soups': 'Soups',
        'Ice cream': 'Ice cream',
        'Offals': 'Offals',
        'Waters and flavored waters': 'Waters and flavored waters',
        'Fruit nectars': 'Fruit nectars',
        'Alcoholic beverages': 'Alcoholic beverages',
        'Unknown': 'Unknown',
        'unknown': 'unknown',
        'Healthier foods': 'Healthier foods',
        'Fiber rich foods': 'Fiber rich foods',
        'Low sugar foods': 'Low sugar foods',
        'Protein rich foods': 'Protein rich foods',
        'Energy rich foods': 'Energy rich foods',
        'Low fat foods': 'Low fat foods',
        'Low salt foods': 'Low salt foods',
        'Low saturated fat foods': 'Low saturated fat foods',
        'No data to show': 'No data to show',
        'energy': 'energy',
        'nutrients': 'nutrients',
        'Distribution_selected_products': 'Distribution of macronutrients of selected products',
        'Distribution_of': 'Distribution of macronutrients of',
        'Probabilities to be correct': 'Probabilities to be correct',
        'Results of prediction model from the image': 'Results of prediction model from the image',
        
    },

    'fr': {
        'choose_country': 'Selectionner un pays',
        'search_product': 'Rechercher un produit',
        'picture_search_beta': 'Recherche par image (en test) 📷',
        'advanced_search': 'Recherche avancee 🔍',
        'browsing_history': 'Historique de navigation',
        'displaying_5_products': 'Affichage de 5 produits',
        'displaying_10_products': 'Affichage de 10 produits',
        'displaying_15_products': 'Affichage de 15 produits',
        'displaying_20_products': 'Affichage de 20 produits',
        'advanced_search_label': 'RECHECHE AVANCEE',
        'choose_pnns_group_1': 'Sélectionner un groupe PNNS 1 (facultatif)',
        'choose_pnns_group_2': 'Sélectionner un groupe PNNS 2 (facultatif)',
        'search_product_optional': 'Rechercher un produit (par exemple « lait ») (facultatif)',
        'choose_nutritious_plan': 'Sélectionner un plan nutritif (facultatif)',
        'energy_kcal_100g': 'Energie kcal/100g',
        'energy-kcal_100g': 'Energie kcal/100g',
        'energy_100g': 'Energie kj/100g',
        'fat_g_100g': 'Gras g/100g',
        'fat_100g': 'Gras g/100g',
        'saturated_fat_g_100g': 'Gras satures g/100g',
        'saturated-fat_100g': 'Gras satures g/100g',
        'carbohydrates_g_100g': 'Glucides g/100g',
        'carbohydrates_100g': 'Glucides g/100g',
        'fiber_g_100g': 'Fibres g/100g',
        'fiber_100g': 'Fibres g/100g',
        'proteins_g_100g': 'Proteines g/100g',
        'proteins_100g': 'Proteines g/100g',
        'salt_g_100g': 'Sel g/100g',
        'salt_100g': 'Sel g/100g',
        'macronutrients_g_100g': 'Macronutriments g/100g',
        'macronutrients_100g': 'Macronutriments g/100g',
        'search': 'Recherche',
        'no_image_available': 'Aucune image disponible',
        'choose_nutrients': 'Selectionnez un nutriment',
        'upload_image': 'Telechargez une image [max 15MB] (.JPEG, .PNG, .JPG)',
        'search_pnns_groups_1': 'Rechercher un groupe PNNS 1',
        'search_pnns_groups_2': 'Rechercher un groupe PNNS 2',
        'clear_image': "Effacer l'image",
        'best_recommended_products': 'MEILLEURS PRODUITS RECOMMANDÉS PAR CATÉGORIE',
        'product_not_found': "Produit non trouvé, recherchez-en un autre",
        'product_not_available': "Le produit n'est pas disponible",
        'product_name': 'Nom du produit',
        'products': 'produits',
        'product_code': 'Code du produit',
        'Composite foods': 'Aliments composites',
        'Fruits and vegetables': 'Fruits et légumes',
        'Cereals and potatoes': 'Céréales et pommes de terre',
        'Fat and sauces': 'Graisses et sauces',
        'Salty snacks': 'Snacks salés',
        'Beverages': 'Boissons',
        'Sugary snacks': 'Snacks sucrés',
        'Fish Meat Eggs': 'Poisson Viande Œufs',
        'Milk and dairy products': 'Produits laitiers',
        'referenced_products': 'Produits référencés',
        "United States": 'Etats-Unis', 
        "France": 'France', 
        "Germany": 'Allemange', 
        "United Kingdom": 'Royaume-Uni',
        'Pizza pies and quiches': 'Pizzas et quiches',
        'Fruits': 'Fruits',
        'Bread': 'Pain',
        'Dressings and sauces': 'Assaisonnements et sauces',
        'Salty and fatty products': 'Produits salés et gras',
        'Sweetened beverages': 'Boissons sucrées',
        'Sweets': 'Friandises',
        'Biscuits and cakes': 'Biscuits et gâteaux',
        'Pastries': 'Pâtisseries',
        'Fish and seafood': 'Poissons et fruits de mer',
        'One-dish meals': 'Plats uniques',
        'Appetizers': 'Apéritifs',
        'Cheese': 'Fromages',
        'Fats': 'Graisses',
        'Processed meat': 'Viandes transformées',
        'Sandwiches': 'Sandwichs',
        'Vegetables': 'Légumes',
        'Breakfast cereals': 'Céréales petit-déjeuner',
        'Chocolate products': 'Produits chocolatés',
        'Unsweetened beverages': 'Boissons non sucrées',
        'Dried fruits': 'Fruits secs',
        'Meat': 'Viande',
        'Cereals': 'Céréales',
        'Eggs': 'Œufs',
        'Plant-based milk substitutes': "Substituts de lait d'origine végétale",
        'Legumes': 'Légumineuses',
        'Teas and herbal teas and coffees': 'Thés, tisanes et cafés',
        'Dairy desserts': 'Desserts lactés',
        'Nuts': 'Fruits à coque',
        'Fruit juices': 'Jus de fruits',
        'Milk and yogurt': 'Lait et yaourts',
        'Artificially sweetened beverages': 'Boissons édulcorées artificiellement',
        'Potatoes': 'Pommes de terre',
        'Soups': 'Soupes',
        'Ice cream': 'Glace',
        'Offals': 'Abats',
        'Waters and flavored waters': 'Eaux et eaux aromatisées',
        'Fruit nectars': 'Nectars de fruits',
        'Alcoholic beverages': 'Boissons alcoolisées',
        'Unknown': 'Inconnu',
        'unknown': 'inconnu',
        'Healthier foods': 'Aliments plus sains',
        'Fiber rich foods': 'Aliments riches en fibres',
        'Low sugar foods': 'Aliments faibles en sucre',
        'Protein rich foods': 'Aliments riches en protéines',
        'Energy rich foods': 'Aliments riches en énergie',
        'Low fat foods': 'Aliments faibles en gras',
        'Low salt foods': 'Aliments faibles en sel',
        'Low saturated fat foods': 'Aliments faibles en gras saturés',
        'No data to show': 'Aucune donnée à afficher',
        'energy': 'énergie',
        'nutrients': 'nutriments',
        'Distribution_selected_products': 'Répartition des macronutriments des produits sélectionnés',
        'Distribution_of': 'Répartition des macronutriments de',
        'Probabilities to be correct': 'Probabilités d\'être correct',
        'Results of prediction model from the image': 'Résultats du modèle de prédiction à partir de l\'image',
        
        
    },
    'de': {
        'choose_country': 'Wählen Sie ein Land',
        'search_product': 'Suchen Sie ein Produkt',
        'picture_search_beta': 'Bildersuche (in Beta) 📷',
        'advanced_search': 'Erweiterte Suche 🔍',
        'browsing_history': 'Verlauf anzeigen',
        'displaying_5_products': 'Anzeige von 5 Produkten',
        'displaying_10_products': 'Anzeige von 10 Produkten',
        'displaying_15_products': 'Anzeige von 15 Produkten',
        'displaying_20_products': 'Anzeige von 20 Produkten',
        'advanced_search_label': 'ERWEITERTE SUCHE',
        'choose_pnns_group_1': 'Wählen Sie eine PNNS-Gruppe 1 (optional)',
        'choose_pnns_group_2': 'Wählen Sie eine PNNS-Gruppe 2 (optional)',
        'search_product_optional': 'Suchen Sie ein Produkt (z.B. \'Milch\') (optional)',
        'choose_nutritious_plan': 'Wählen Sie einen nahrhaften Plan (optional)',
        'energy_kcal_100g': 'Energie kcal/100g',
        'energy-kcal_100g': 'Energie kcal/100g',
        'fat_g_100g': 'Fett g/100g',
        'saturated_fat_g_100g': 'Gesättigtes Fett g/100g',
        'carbohydrates_g_100g': 'Kohlenhydrate g/100g',
        'fiber_g_100g': 'Ballaststoffe g/100g',
        'proteins_g_100g': 'Proteine g/100g',
        'salt_g_100g': 'Salz g/100g',
        'macronutrients_g_100g': 'Makronährstoffe g/100g',
        'energy_100g': 'Energie kj/100g',
        'fat_100g': 'Fett g/100g',
        'saturated-fat_100g': 'Gesättigtes Fett g/100g',
        'carbohydrates_100g': 'Kohlenhydrate g/100g',
        'fiber_100g': 'Ballaststoffe g/100g',
        'proteins_100g': 'Proteine g/100g',
        'salt_100g': 'Salz g/100g',
        'macronutrients_100g': 'Makronährstoffe g/100g',
        'search': 'Suche',
        'no_image_available': 'Kein Bild verfügbar',
        'choose_nutrients': 'Nährstoffe auswählen',
        'upload_image': 'Bild hochladen [max. 15 MB] (.JPEG, .PNG, .JPG)',
        'search_pnns_groups_1': 'Suche pnns_groups_1',
        'search_pnns_groups_2': 'Suche pnns_groups_2',
        'clear_image': 'Bild löschen',
        'best_recommended_products': 'BEST EMPFOHLENE PRODUKTE NACH KATEGORIE',
        'product_not_found': "Produkt nicht gefunden, suchen Sie nach einem anderen",
        'product_not_available': "Das Produkt ist nicht verfügbar",
        'product_name': 'Produktname',
        'products': 'produkt',
        'product_code': 'Produktcode',
        'Composite foods': 'Zusammengesetzte Lebensmittel',
        'Fruits and vegetables': 'Obst und Gemüse',
        'Cereals and potatoes': 'Getreide und Kartoffeln',
        'Fat and sauces': 'Fett und Saucen',
        'Salty snacks': 'Herzhafte Snacks',
        'Beverages': 'Getränke',
        'Sugary snacks': 'Süße Snacks',
        'Fish Meat Eggs': 'Fisch Fleisch Eier',
        'Milk and dairy products': 'Milch und Milchprodukte',
        'referenced_products': 'Referenzierte Produkte',
        'United States': 'Vereinigte Staaten',
        'France': 'Frankreich',
        'Germany': 'Deutschland',
        'United Kingdom': 'Vereinigtes Königreich',
        'Pizza pies and quiches': 'Pizzas und Quiches',
        'Fruits': 'Früchte',
        'Bread': 'Brot',
        'Dressings and sauces': 'Dressings und Saucen',
        'Salty and fatty products': 'Salzige und fettige Produkte',
        'Sweetened beverages': 'Gesüßte Getränke',
        'Sweets': 'Süßigkeiten',
        'Biscuits and cakes': 'Kekse und Kuchen',
        'Pastries': 'Gebäck',
        'Fish and seafood': 'Fisch und Meeresfrüchte',
        'One-dish meals': 'Eingetopfte Gerichte',
        'Appetizers': 'Vorspeisen',
        'Cheese': 'Käse',
        'Fats': 'Fette',
        'Processed meat': 'Verarbeitetes Fleisch',
        'Sandwiches': 'Sandwiches',
        'Vegetables': 'Gemüse',
        'Breakfast cereals': 'Frühstücksflocken',
        'Chocolate products': 'Schokoladenprodukte',
        'Unsweetened beverages': 'Ungesüßte Getränke',
        'Dried fruits': 'Getrocknete Früchte',
        'Meat': 'Fleisch',
        'Cereals': 'Getreide',
        'Eggs': 'Eier',
        'Plant-based milk substitutes': 'Pflanzliche Milchersatzprodukte',
        'Legumes': 'Hülsenfrüchte',
        'Teas and herbal teas and coffees': 'Tees, Kräutertees und Kaffees',
        'Dairy desserts': 'Milchdesserts',
        'Nuts': 'Nüsse',
        'Fruit juices': 'Fruchtsäfte',
        'Milk and yogurt': 'Milch und Joghurt',
        'Artificially sweetened beverages': 'Künstlich gesüßte Getränke',
        'Potatoes': 'Kartoffeln',
        'Soups': 'Suppen',
        'Ice cream': 'Eis',
        'Offals': 'Innereien',
        'Waters and flavored waters': 'Wasser und aromatisierte Wasser',
        'Fruit nectars': 'Fruchtnektare',
        'Alcoholic beverages': 'Alkoholische Getränke',
        'Unknown': 'Unbekannt',
        'unknown': 'unbekannt',
        'Healthier foods': 'Gesündere Lebensmittel',
        'Fiber rich foods': 'Ballaststoffreiche Lebensmittel',
        'Low sugar foods': 'Lebensmittel mit wenig Zucker',
        'Protein rich foods': 'Proteinreiche Lebensmittel',
        'Energy rich foods': 'Energierreiche Lebensmittel',
        'Low fat foods': 'Fettarme Lebensmittel',
        'Low salt foods': 'Lebensmittel mit wenig Salz',
        'Low saturated fat foods': 'Lebensmittel mit wenig gesättigtem Fett',
        'No data to show': 'Keine Daten vorhanden',
        'energy': 'energie',
        'nutrients': 'nährstoffe',
        'Distribution_selected_products': 'Verteilung der Makronährstoffe ausgewählter Produkte',
        'Distribution_of': 'Verteilung der Makronährstoffe von',
        'Probabilities to be correct': 'Wahrscheinlichkeiten, richtig zu sein',
        'Results of prediction model from the image': 'Ergebnisse des Vorhersagemodells aus dem Bild',
        
        
    },
    'da': {
        'choose_country': 'Vælg et land',
        'search_product': 'Søg efter et produkt',
        'picture_search_beta': 'Billedsøgning (i beta) 📷',
        'advanced_search': 'Avanceret søgning 🔍',
        'browsing_history': 'Gennemse historik',
        'displaying_5_products': 'Viser 5 produkter',
        'displaying_10_products': 'Viser 10 produkter',
        'displaying_15_products': 'Viser 15 produkter',
        'displaying_20_products': 'Viser 20 produkter',
        'advanced_search_label': 'AVANCERET SØGNING',
        'choose_pnns_group_1': 'Vælg en PNNS-gruppe 1 (valgfri)',
        'choose_pnns_group_2': 'Vælg en PNNS-gruppe 2 (valgfri)',
        'search_product_optional': 'Søg efter et produkt (f.eks. \'mælk\') (valgfri)',
        'choose_nutritious_plan': 'Vælg en ernæringsmæssig plan (valgfri)',
        'energy_kcal_100g': 'Energi kcal/100g',
        'energy-kcal_100g': 'Energi kcal/100g',
        'fat_g_100g': 'Fedt g/100g',
        'saturated_fat_g_100g': 'Mættet fedt g/100g',
        'carbohydrates_g_100g': 'Kulhydrater g/100g',
        'fiber_g_100g': 'Fiber g/100g',
        'proteins_g_100g': 'Proteiner g/100g',
        'salt_g_100g': 'Salt g/100g',
        'macronutrients_g_100g': 'Macronæringsstoffer g/100g',
        'energy_100g': 'Energi kj/100g',
        'fat_100g': 'Fedt g/100g',
        'saturated-fat_100g': 'Mættet fedt g/100g',
        'carbohydrates_100g': 'Kulhydrater g/100g',
        'fiber_100g': 'Fiber g/100g',
        'proteins_100g': 'Proteiner g/100g',
        'salt_100g': 'Salt g/100g',
        'macronutrients_100g': 'Macronæringsstoffer g/100g',
        'search': 'Søg',
        'no_image_available': 'Ingen billede tilgængelig',
        'choose_nutrients': 'Vælg næringsstoffer',
        'upload_image': 'Upload billede [maks. 15 MB] (.JPEG, .PNG, .JPG)',
        'search_pnns_groups_1': 'Søg pnns_groups_1',
        'search_pnns_groups_2': 'Søg pnns_groups_2',
        'clear_image': 'Ryd billede',
        'best_recommended_products': 'BEDSTE ANBEFALEDE PRODUKTER PR. KATEGORI',
        'product_not_found': "Produktet blev ikke fundet, søg efter et andet",
        'product_not_available': "Produktet er ikke tilgængeligt",
        'product_name': 'Produktnavn',
        'products': 'produkt',
        'product_code': 'Produktkode',
        'Composite foods': 'Sammensatte fødevarer',
        'Fruits and vegetables': 'Frugt og grøntsager',
        'Cereals and potatoes': 'Korn og kartofler',
        'Fat and sauces': 'Fedt og saucer',
        'Salty snacks': 'Salte snacks',
        'Beverages': 'Drikkevarer',
        'Sugary snacks': 'Søde snacks',
        'Fish Meat Eggs': 'Fisk Kød Æg',
        'Milk and dairy products': 'Mælk og mejeriprodukter',
        'referenced_products': 'Refererede produkter',
        'United States': 'USA',
        'France': 'Frankrig',
        'Germany': 'Tyskland',
        'United Kingdom': 'Storbritannien',
        'Pizza pies and quiches': 'Pizzaer og tærter',
        'Fruits': 'Frugter',
        'Bread': 'Brød',
        'Dressings and sauces': 'Dressinger og saucer',
        'Salty and fatty products': 'Salte og fede produkter',
        'Sweetened beverages': 'Sødede drikkevarer',
        'Sweets': 'Slik',
        'Biscuits and cakes': 'Kiks og kager',
        'Pastries': 'Wienerbrød',
        'Fish and seafood': 'Fisk og skaldyr',
        'One-dish meals': 'Én-retters måltider',
        'Appetizers': 'Forretter',
        'Cheese': 'Ost',
        'Fats': 'Fedtstoffer',
        'Processed meat': 'Forarbejdet kød',
        'Sandwiches': 'Sandwiches',
        'Vegetables': 'Grøntsager',
        'Breakfast cereals': 'Morgenmadsprodukter',
        'Chocolate products': 'Chokoladeprodukter',
        'Unsweetened beverages': 'Usødede drikkevarer',
        'Dried fruits': 'Tørret frugt',
        'Meat': 'Kød',
        'Cereals': 'Kornprodukter',
        'Eggs': 'Æg',
        'Plant-based milk substitutes': 'Plantebaserede mælk erstatninger',
        'Legumes': 'Bælgfrugter',
        'Teas and herbal teas and coffees': 'Te, urtete og kaffe',
        'Dairy desserts': 'Mejeri desserter',
        'Nuts': 'Nødder',
        'Fruit juices': 'Frugtsaft',
        'Milk and yogurt': 'Mælk og yoghurt',
        'Artificially sweetened beverages': 'Artificielt sødede drikkevarer',
        'Potatoes': 'Kartofler',
        'Soups': 'Supper',
        'Ice cream': 'Is',
        'Offals': 'Indmad',
        'Waters and flavored waters': 'Vand og smagsgivet vand',
        'Fruit nectars': 'Frugtnektarer',
        'Alcoholic beverages': 'Alkoholholdige drikkevarer',
        'Unknown': 'Ukendt',
        'unknown': 'ukendt',
        'Healthier foods': 'Sundere fødevarer',
        'Fiber rich foods': 'Fiber rige fødevarer',
        'Low sugar foods': 'Fødevarer med lavt sukkerindhold',
        'Protein rich foods': 'Proteinrige fødevarer',
        'Energy rich foods': 'Energi rige fødevarer',
        'Low fat foods': 'Fedtfattige fødevarer',
        'Low salt foods': 'Fødevarer med lavt saltindhold',
        'Low saturated fat foods': 'Fødevarer med lavt indhold af mættet fedt',
        'No data to show': 'Ingen data at vise',
        'energy': 'energi',
        'nutrients': 'næringsstoffer',
        'Distribution_selected_products': 'Fordeling af makronæringsstoffer i udvalgte produkter',
        'Distribution_of': 'Fordeling af makronæringsstoffer i',
        'Probabilities to be correct': 'Sandsynligheder for at være korrekt',
        'Results of prediction model from the image': 'Resultater af forudsigelsesmodellen fra billedet',
        
       
    }
}
